export const COLORS = {
  background: '#F5F7FA',         
  inputBackground: '#E0E7EF',    
  inputText: '#1F2D3D',          
  error: '#FF5A5F',              
  button: '#0052CC',             
  divider: '#C5D1E0',            
  textMuted: '#0052CC',          
  item: '#E8F0FE',               
  shadowCardapio: '#1F2D3D',     
  preco: '#00B894',              
  favButton: '#D0E6FF',          
  favAtivo: '#4DA3FF',           
  telaCardapio: '#F0F4FA',       
  telaHome: '#F0F4FA',
  telaFavoritos: '#F0F4FA',
};
